version: '3.5'

services:
    server:
      container_name: server
      build: ./server/.
      image: reversessh/server:0.1
      expose:
        - 12345
        - 22

    client:
      container_name: client
      build: ./client/.
      image: reversessh/client:0.1
      depends_on:
        - server
      expose:
        - 22
